/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Proccess.Hanghoa;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class frHanghoa extends javax.swing.JFrame {

    /**
     * Creates new form frSanphamKhohang
     */
    public frHanghoa() {
        initComponents();
        setLocationRelativeTo(null);  //dieu chinh form ra giua man hinhf
        loadDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNhap = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHanghoa = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnLammoi = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnThem = new javax.swing.JButton();
        btnSuathongtin = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtTinhtrang = new javax.swing.JTextField();
        txtDonvitinh = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMahanghoa = new javax.swing.JTextField();
        txtTenhanghoa = new javax.swing.JTextField();
        txtSoluong = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnTimkiem = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kho hàng");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 160, -1));

        tableHanghoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Hàng", "Tên Hàng", "Đơn vị tính", "Giá", "Số lượng", "Tình trạng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableHanghoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableHanghoaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableHanghoa);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 630, 140));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLammoi.setBackground(new java.awt.Color(255, 255, 255));
        btnLammoi.setForeground(new java.awt.Color(0, 0, 0));
        btnLammoi.setText("Làm mới");
        btnLammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiActionPerformed(evt);
            }
        });
        jPanel2.add(btnLammoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 120, -1));

        jLabel7.setBackground(new java.awt.Color(102, 102, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tạo đơn hàng");
        jLabel7.setToolTipText("hàng");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 30, 150, -1));

        btnThem.setBackground(new java.awt.Color(255, 255, 255));
        btnThem.setForeground(new java.awt.Color(0, 0, 0));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel2.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, -1));

        btnSuathongtin.setBackground(new java.awt.Color(255, 255, 255));
        btnSuathongtin.setForeground(new java.awt.Color(0, 0, 0));
        btnSuathongtin.setText("Sửa Thông tin");
        btnSuathongtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuathongtinActionPerformed(evt);
            }
        });
        jPanel2.add(btnSuathongtin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, -1));

        btnXoa.setBackground(new java.awt.Color(255, 255, 255));
        btnXoa.setForeground(new java.awt.Color(0, 0, 0));
        btnXoa.setText("Xóa ");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel2.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 120, -1));

        btnThoat.setBackground(new java.awt.Color(255, 255, 255));
        btnThoat.setForeground(new java.awt.Color(0, 0, 0));
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel2.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 120, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 140, 240));

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51)));

        txtTinhtrang.setForeground(new java.awt.Color(0, 0, 0));

        txtDonvitinh.setForeground(new java.awt.Color(0, 0, 0));

        txtGia.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Đơn vị tính :");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tình trạng :");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Giá :");

        txtMahanghoa.setForeground(new java.awt.Color(0, 0, 0));

        txtTenhanghoa.setForeground(new java.awt.Color(0, 0, 0));

        txtSoluong.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Mã hàng hóa :");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tên hàng hóa :");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText(" Số lượng :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMahanghoa))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenhanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30)
                        .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDonvitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTinhtrang, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDonvitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTinhtrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMahanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenhanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSoluong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(69, 69, 69))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 490, 190));

        btnTimkiem.setBackground(java.awt.SystemColor.control);
        btnTimkiem.setForeground(new java.awt.Color(0, 0, 0));
        btnTimkiem.setText("Tìm kiếm ");
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });
        jPanel1.add(btnTimkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 100, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nhập tên hàng hóa :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadDataToTable() {
        try {
            Hanghoa HanghoaModel = new Hanghoa();
            List<Hanghoa> list = HanghoaModel.getHanghoa();
            // Lấy mô hình bảng (table model) và xóa dữ liệu cũ
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tableHanghoa.getModel();

            model.setColumnIdentifiers(new Object[]{"STT", "Mã Hàng", "Tên Hàng", "Số lượng", "Giá", "Đơn vị tính", "Tình trạng"});
            model.setRowCount(0);

            // Thêm các hàng dữ liệu mới vào bảng
            int stt = 1;
            for (Hanghoa hh : list) {
                model.addRow(new Object[]{
                    stt++, hh.getMahh(), hh.getTenhh(), hh.getSoluong(),
                    hh.getGia(), hh.getDonvt(), hh.getTinhtrang()});
            }
        } catch (SQLException e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu vào bảng.");
        }
    }
    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        String Nhaptenhh = txtNhap.getText().trim();  // Lấy tên nhập vào từ TextField
        if (Nhaptenhh.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập tên hàng  để tìm kiếm.");
            return;
        }

        try {
            // Tạo đối tượng Nhanvien
            Hanghoa hh = new Hanghoa();

            // Gọi phương thức timKiemhanghoaTheoTen thông qua đối tượng
            List<Hanghoa> dshanghoa = hh.timKiemHanghoa(Nhaptenhh);

            // Xóa dữ liệu hiện có trong bảng
            DefaultTableModel modelHanghoa = (DefaultTableModel) tableHanghoa.getModel();
            modelHanghoa.setRowCount(0);

            // Thêm kết quả tìm kiếm vào bảng
            for (Hanghoa n : dshanghoa) {
                modelHanghoa.addRow(new Object[]{n.getMahh(), n.getTenhh(), n.getSoluong(), n.getGia(), n.getDonvt(), n.getTinhtrang()});
            }

            // Hiển thị thông báo nếu không tìm thấy
            if (dshanghoa.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên nào có tên: " + Nhaptenhh);
            }

        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi khi tìm kiếm nhân viên: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String mahh = txtMahanghoa.getText();
        String tenhh = txtTenhanghoa.getText();
        int soluong = Integer.parseInt(txtSoluong.getText());
        double gia = Double.parseDouble(txtGia.getText());
        String donvitinh = txtDonvitinh.getText();
        String tinhtrang = txtTinhtrang.getText();

        if (mahh.isEmpty() || tenhh.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, " Vui long nhap  day du thong tin");
        } else {
            try {
                Hanghoa hanghoa = new Hanghoa();
                if (hanghoa.getHanghoa(mahh) != null) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Mã loại đã tồn tại. Vui lòng nhập mã khác !");
                    return;
                }
                // thiet lap gia tri
                hanghoa.setMahh(mahh);
                hanghoa.setTenhh(tenhh);
                hanghoa.setSoluong(soluong);
                hanghoa.setGia(gia);
                hanghoa.setDonvt(donvitinh);
                hanghoa.setTinhtrang(tinhtrang);

                // goi ham tu lop hanghoa
                if (hanghoa.InsertHanghoa(hanghoa)) {
                    loadDataToTable();

                    txtMahanghoa.setText("");
                    txtTenhanghoa.setText("");
                    txtSoluong.setText("");
                    txtGia.setText("");
                    txtDonvitinh.setText("");
                    txtTinhtrang.setText("");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Them that bai!");
                }
            } catch (Exception e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, " Loi !");
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuathongtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuathongtinActionPerformed
        int row = tableHanghoa.getSelectedRow();
        //kiem tra
        if (row != -1) {
            String mahh = txtMahanghoa.getText();
            String tenhh = txtTenhanghoa.getText();
            int soluong = Integer.parseInt(txtSoluong.getText());
            double gia = Double.parseDouble(txtGia.getText());
            String donvitinh = txtDonvitinh.getText();
            String tinhtrang = txtTinhtrang.getText();
            if (mahh.isEmpty() || tenhh.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin ");
            } else {
                try {
                    Hanghoa hanghoa = new Hanghoa();

                    // thiet lap gia tri
                    hanghoa.setMahh(mahh);
                    hanghoa.setTenhh(tenhh);
                    hanghoa.setSoluong(soluong);
                    hanghoa.setGia(gia);
                    hanghoa.setDonvt(donvitinh);
                    hanghoa.setTinhtrang(tinhtrang);

                    //goi ham 
                    if (hanghoa.EditHanghoa(hanghoa)) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Sửa thành công.");
                        //cap nhat vao bang
                        tableHanghoa.setValueAt(mahh, row, 1);
                        tableHanghoa.setValueAt(tenhh, row, 2);
                        tableHanghoa.setValueAt(soluong, row, 3);
                        tableHanghoa.setValueAt(gia, row, 4);
                        tableHanghoa.setValueAt(donvitinh, row, 5);
                        tableHanghoa.setValueAt(tinhtrang, row, 6);
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "Sửa thất bại.");
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    javax.swing.JOptionPane.showMessageDialog(this, "Lỗi trong quá trình sửa.");
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn hàng để sửa.");
        }
    }//GEN-LAST:event_btnSuathongtinActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = tableHanghoa.getSelectedRow();
        if (row != -1) {
            String maHH = tableHanghoa.getValueAt(row, 0).toString(); // Lay ma tu table
            try {
                Hanghoa hh = new Hanghoa();
                if (hh.DeleteHanghoa(maHH)) {
                    javax.swing.JOptionPane.showConfirmDialog(this, " xoa thanh cong !");
                    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tableHanghoa.getModel();
                    model.removeRow(row);
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, " xoa that bai !!!");
                }
            } catch (Exception e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Lỗi trong quá trình xóa.");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn hàng để xóa.");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiActionPerformed
        txtMahanghoa.setText("");
        txtTenhanghoa.setText("");
        txtSoluong.setText("");
        txtGia.setText("");
        txtDonvitinh.setText("");
        txtTinhtrang.setText("");
    }//GEN-LAST:event_btnLammoiActionPerformed

    private void tableHanghoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableHanghoaMouseClicked
        int selectedRow = tableHanghoa.getSelectedRow(); // Lấy chỉ số dòng được chọn

        if (selectedRow != -1) { // Kiểm tra xem có dòng nào được chọn hay không
            String mahh = tableHanghoa.getValueAt(selectedRow, 1).toString();
            String tenhh = tableHanghoa.getValueAt(selectedRow, 2).toString();
            String soluong = tableHanghoa.getValueAt(selectedRow, 3).toString();
            String gia = tableHanghoa.getValueAt(selectedRow, 4).toString();
            String donvitinh = tableHanghoa.getValueAt(selectedRow, 5).toString();
            String tinhtrang = tableHanghoa.getValueAt(selectedRow, 6).toString();

            // Set các giá trị cho các JTextField
            txtMahanghoa.setText(mahh);
            txtTenhanghoa.setText(tenhh);
            txtSoluong.setText(soluong);
            txtGia.setText(gia);
            txtDonvitinh.setText(donvitinh);
            txtTinhtrang.setText(tinhtrang);
        }
    }//GEN-LAST:event_tableHanghoaMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frHanghoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frHanghoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frHanghoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frHanghoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frHanghoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLammoi;
    private javax.swing.JButton btnSuathongtin;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tableHanghoa;
    private javax.swing.JTextField txtDonvitinh;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMahanghoa;
    private javax.swing.JTextField txtNhap;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtTenhanghoa;
    private javax.swing.JTextField txtTinhtrang;
    // End of variables declaration//GEN-END:variables
}
