/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Proccess.Hanghoa;
import java.sql.SQLException;
import java.util.List;

/**
 *
 * @author Lenovo
 */
public class frHanghoa extends javax.swing.JFrame {

    /**
     * Creates new form frSanphamKhohang
     */
    public frHanghoa() {
        initComponents();
        setLocationRelativeTo(null);  //dieu chinh form ra giua man hinhf
        loadDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNhap = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHanghoa = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnThoat = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnThem = new javax.swing.JButton();
        btnSuathongtin = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnNhaphang2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtTinhtrang = new javax.swing.JTextField();
        txtDonvitinh = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMahanghoa = new javax.swing.JTextField();
        txtTenhanghoa = new javax.swing.JTextField();
        txtSoluong = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnTimkiem = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kho hàng");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 180, -1));

        tableHanghoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Hàng", "Tên Hàng", "Đơn vị tính", "Giá", "Số lượng", "Tình trạng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableHanghoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableHanghoaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableHanghoa);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 570, 140));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnThoat.setBackground(java.awt.SystemColor.activeCaption);
        btnThoat.setForeground(new java.awt.Color(0, 0, 0));
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel2.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 120, -1));

        jLabel7.setBackground(new java.awt.Color(102, 102, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tạo đơn hàng");
        jLabel7.setToolTipText("hàng");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 30, 150, -1));

        btnThem.setBackground(java.awt.SystemColor.activeCaption);
        btnThem.setForeground(new java.awt.Color(0, 0, 0));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel2.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, -1));

        btnSuathongtin.setBackground(java.awt.SystemColor.activeCaption);
        btnSuathongtin.setForeground(new java.awt.Color(0, 0, 0));
        btnSuathongtin.setText("Sửa Thông tin");
        btnSuathongtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuathongtinActionPerformed(evt);
            }
        });
        jPanel2.add(btnSuathongtin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, -1));

        btnXoa.setBackground(java.awt.SystemColor.activeCaption);
        btnXoa.setForeground(new java.awt.Color(0, 0, 0));
        btnXoa.setText("Xóa ");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel2.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 120, -1));

        btnNhaphang2.setBackground(java.awt.SystemColor.activeCaption);
        btnNhaphang2.setForeground(new java.awt.Color(0, 0, 0));
        btnNhaphang2.setText("Nhập hàng");
        jPanel2.add(btnNhaphang2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 120, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 140, 240));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel6.setText("Đơn vị tính :");

        jLabel4.setText("Tình trạng :");

        jLabel5.setText("Giá :");

        jLabel1.setText("Mã hàng hóa :");

        jLabel2.setText("Tên hàng hóa :");

        jLabel3.setText(" Số lượng :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMahanghoa, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(9, 9, 9))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenhanghoa, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(txtSoluong))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDonvitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTinhtrang, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtMahanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDonvitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenhanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTinhtrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(49, 49, 49))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 430, 170));

        btnTimkiem.setBackground(java.awt.SystemColor.activeCaption);
        btnTimkiem.setForeground(new java.awt.Color(0, 0, 0));
        btnTimkiem.setText("Tìm kiếm ");
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });
        jPanel1.add(btnTimkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 90, -1));

        jLabel8.setText("Nhập tên hàng hóa :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadDataToTable() {
        try {
            Hanghoa HanghoaModel = new Hanghoa();
            List<Hanghoa> list = HanghoaModel.getHanghoa();
            // Lấy mô hình bảng (table model) và xóa dữ liệu cũ
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tableHanghoa.getModel();

            model.setColumnIdentifiers(new Object[]{"STT", "Mã Hàng", "Tên Hàng", "Số lượng", "Giá", "Đơn vị tính", "Tình trạng"});
            model.setRowCount(0);

            // Thêm các hàng dữ liệu mới vào bảng
            int stt = 1;
            for (Hanghoa hh : list) {
                model.addRow(new Object[]{
                    stt++, hh.getMahh(), hh.getTenhh(), hh.getSoluong(),
                    hh.getGia(), hh.getDonvt(), hh.getTinhtrang()});
            }
        } catch (SQLException e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu vào bảng.");
        }
    }
    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String mahh = txtMahanghoa.getText();
        String tenhh = txtTenhanghoa.getText();
        int soluong = Integer.parseInt(txtSoluong.getText());
        double gia = Double.parseDouble(txtGia.getText());
        String donvitinh = txtDonvitinh.getText();
        String tinhtrang = txtTinhtrang.getText();

        if (mahh.isEmpty() || tenhh.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, " Vui long nhap  day du thong tin");
        } else {
            try {
                Hanghoa hanghoa = new Hanghoa();
                if (hanghoa.getHanghoa(mahh) != null) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Mã loại đã tồn tại. Vui lòng nhập mã khác !");
                    return;
                }
                // thiet lap gia tri
                hanghoa.setMahh(mahh);
                hanghoa.setTenhh(tenhh);
                hanghoa.setSoluong(soluong);
                hanghoa.setGia(gia);
                hanghoa.setDonvt(donvitinh);
                hanghoa.setTinhtrang(tinhtrang);

                // goi ham tu lop hanghoa
                if (hanghoa.InsertHanghoa(hanghoa)) {
                    loadDataToTable();

                    txtMahanghoa.setText("");
                    txtTenhanghoa.setText("");
                    txtSoluong.setText("");
                    txtGia.setText("");
                    txtDonvitinh.setText("");
                    txtTinhtrang.setText("");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Them that bai!");
                }
            } catch (Exception e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, " Loi !");
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuathongtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuathongtinActionPerformed
        int row = tableHanghoa.getSelectedRow();
        //kiem tra
        if (row != -1) {
            String mahh = txtMahanghoa.getText();
            String tenhh = txtTenhanghoa.getText();
            int soluong = Integer.parseInt(txtSoluong.getText());
            double gia = Double.parseDouble(txtGia.getText());
            String donvitinh = txtDonvitinh.getText();
            String tinhtrang = txtTinhtrang.getText();
            if (mahh.isEmpty() || tenhh.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin ");
            } else {
                try {
                    Hanghoa hanghoa = new Hanghoa();

                    // thiet lap gia tri
                    hanghoa.setMahh(mahh);
                    hanghoa.setTenhh(tenhh);
                    hanghoa.setSoluong(soluong);
                    hanghoa.setGia(gia);
                    hanghoa.setDonvt(donvitinh);
                    hanghoa.setTinhtrang(tinhtrang);

                    //goi ham 
                    if (hanghoa.EditHanghoa(hanghoa)) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Sửa thành công.");
                        //cap nhat vao bang
                        tableHanghoa.setValueAt(mahh, row, 1);
                        tableHanghoa.setValueAt(tenhh, row, 2);
                        tableHanghoa.setValueAt(soluong, row, 3);
                        tableHanghoa.setValueAt(gia, row, 4);
                        tableHanghoa.setValueAt(donvitinh, row, 5);
                        tableHanghoa.setValueAt(tinhtrang, row, 6);
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "Sửa thất bại.");
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    javax.swing.JOptionPane.showMessageDialog(this, "Lỗi trong quá trình sửa.");
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn hàng để sửa.");
        }
    }//GEN-LAST:event_btnSuathongtinActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = tableHanghoa.getSelectedRow();
        if (row != -1) {
            String maHH = tableHanghoa.getValueAt(row, 0).toString(); // Lay ma tu table
            try {
                Hanghoa hh = new Hanghoa();
                if (hh.DeleteHanghoa(maHH)) {
                    javax.swing.JOptionPane.showConfirmDialog(this, " xoa thanh cong !");
                    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tableHanghoa.getModel();
                    model.removeRow(row);
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, " xoa that bai !!!");
                }
            } catch (Exception e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Lỗi trong quá trình xóa.");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn hàng để xóa.");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void tableHanghoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableHanghoaMouseClicked
        int selectedRow = tableHanghoa.getSelectedRow(); // Lấy chỉ số dòng được chọn

        if (selectedRow != -1) { // Kiểm tra xem có dòng nào được chọn hay không
            String mahh = tableHanghoa.getValueAt(selectedRow, 1).toString();
            String tenhh = tableHanghoa.getValueAt(selectedRow, 2).toString();
            String soluong = tableHanghoa.getValueAt(selectedRow, 3).toString();
            String gia = tableHanghoa.getValueAt(selectedRow, 4).toString();
            String donvitinh = tableHanghoa.getValueAt(selectedRow, 5).toString();
            String tinhtrang = tableHanghoa.getValueAt(selectedRow, 6).toString();

            // Set các giá trị cho các JTextField
            txtMahanghoa.setText(mahh);
            txtTenhanghoa.setText(tenhh);
            txtSoluong.setText(soluong);
            txtGia.setText(gia);
            txtDonvitinh.setText(donvitinh);
            txtTinhtrang.setText(tinhtrang);
        }
    }//GEN-LAST:event_tableHanghoaMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frHanghoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frHanghoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frHanghoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frHanghoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frHanghoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNhaphang2;
    private javax.swing.JButton btnSuathongtin;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tableHanghoa;
    private javax.swing.JTextField txtDonvitinh;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMahanghoa;
    private javax.swing.JTextField txtNhap;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtTenhanghoa;
    private javax.swing.JTextField txtTinhtrang;
    // End of variables declaration//GEN-END:variables
}
