/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

/**
 *
 * @author Lenovo
 */
public class PanelPhieuxuat extends javax.swing.JPanel {

    /**
     * Creates new form PanelPhieuxuat
     */
    public PanelPhieuxuat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPhieuxuat = new javax.swing.JLabel();
        PanelPhieuxuat = new javax.swing.JPanel();
        lblMahang = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePhieunhap = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        lblPhieuxuat.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPhieuxuat.setForeground(new java.awt.Color(0, 0, 0));
        lblPhieuxuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhieuxuat.setText("Phiếu xuất");

        PanelPhieuxuat.setBackground(new java.awt.Color(255, 255, 255));
        PanelPhieuxuat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        lblMahang.setForeground(new java.awt.Color(0, 0, 0));
        lblMahang.setText("Mã hàng :");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Số phiếu nhập :");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Số lượng xuất nhập :");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Số lượng thực nhập :");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Giá :");

        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));

        tablePhieunhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hàng", "Số phiếu nhập", "Số lượng xuất nhập", "Số lượng thực nhập", "Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePhieunhap);

        javax.swing.GroupLayout PanelPhieuxuatLayout = new javax.swing.GroupLayout(PanelPhieuxuat);
        PanelPhieuxuat.setLayout(PanelPhieuxuatLayout);
        PanelPhieuxuatLayout.setHorizontalGroup(
            PanelPhieuxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPhieuxuatLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(PanelPhieuxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(lblMahang)
                    .addComponent(jLabel3))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelPhieuxuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        PanelPhieuxuatLayout.setVerticalGroup(
            PanelPhieuxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPhieuxuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMahang)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPhieuxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PanelPhieuxuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblPhieuxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelPhieuxuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPhieuxuat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMahang;
    private javax.swing.JLabel lblPhieuxuat;
    private javax.swing.JTable tablePhieunhap;
    // End of variables declaration//GEN-END:variables
}
