/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

/**
 *
 * @author Lenovo
 */
public class PanelPhieuxuat extends javax.swing.JPanel {

    /**
     * Creates new form PanelPhieuxuat
     */
    public PanelPhieuxuat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPhieuxuat = new javax.swing.JLabel();
        PanelPhieuxuat = new javax.swing.JPanel();
        lblMahang = new javax.swing.JLabel();
        lblSophieuxuat = new javax.swing.JLabel();
        lblSoluongxuat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePhieunhap = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        lblPhieuxuat.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPhieuxuat.setForeground(new java.awt.Color(0, 0, 0));
        lblPhieuxuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhieuxuat.setText("Phiếu xuất");

        PanelPhieuxuat.setBackground(new java.awt.Color(255, 255, 255));
        PanelPhieuxuat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        lblMahang.setForeground(new java.awt.Color(0, 0, 0));
        lblMahang.setText("Mã hàng :");

        lblSophieuxuat.setForeground(new java.awt.Color(0, 0, 0));
        lblSophieuxuat.setText("Số phiếu xuất :");

        lblSoluongxuat.setForeground(new java.awt.Color(0, 0, 0));
        lblSoluongxuat.setText("Số lượng xuất :");

        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));

        tablePhieunhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hàng", "Số phiếu xuất", "Số lượng xuất "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePhieunhap);

        javax.swing.GroupLayout PanelPhieuxuatLayout = new javax.swing.GroupLayout(PanelPhieuxuat);
        PanelPhieuxuat.setLayout(PanelPhieuxuatLayout);
        PanelPhieuxuatLayout.setHorizontalGroup(
            PanelPhieuxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPhieuxuatLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(PanelPhieuxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSoluongxuat)
                    .addComponent(lblSophieuxuat)
                    .addComponent(lblMahang))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelPhieuxuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelPhieuxuatLayout.setVerticalGroup(
            PanelPhieuxuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPhieuxuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMahang)
                .addGap(18, 18, 18)
                .addComponent(lblSophieuxuat)
                .addGap(18, 18, 18)
                .addComponent(lblSoluongxuat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPhieuxuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lblPhieuxuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblPhieuxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelPhieuxuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPhieuxuat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMahang;
    private javax.swing.JLabel lblPhieuxuat;
    private javax.swing.JLabel lblSoluongxuat;
    private javax.swing.JLabel lblSophieuxuat;
    private javax.swing.JTable tablePhieunhap;
    // End of variables declaration//GEN-END:variables
}
