/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

import Proccess.Nhanvien;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class PanelNhanvien extends javax.swing.JPanel {

    /**
     * Creates new form PanelNhanvien
     */
    public PanelNhanvien() {
        initComponents();
        loadDataToTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNhanvien = new javax.swing.JTable();
        btnSua = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTennhanvien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtManhanvien = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtChucvu = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSodienthoai = new javax.swing.JTextField();
        txtDiachi = new javax.swing.JTextField();
        btnTimkiem = new javax.swing.JButton();
        txtNhaptennv = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        radioNam = new javax.swing.JRadioButton();
        radioNu = new javax.swing.JRadioButton();
        btnLammoi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();

        setBackground(java.awt.SystemColor.activeCaptionBorder);
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(617, 390));

        tableNhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Chức vụ", "Số điện thoại", "Email", "Địa chỉ", "Giới tính"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableNhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNhanvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableNhanvien);

        btnSua.setForeground(new java.awt.Color(0, 0, 0));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jPanel1.setBackground(java.awt.SystemColor.controlHighlight);
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Địa chỉ :");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Email :");

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Mã nhân viên :");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tên nhân viên :");

        txtTennhanvien.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Chức vụ :");
        jLabel3.setToolTipText("");

        txtManhanvien.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Số điện thoại :");

        txtChucvu.setForeground(new java.awt.Color(0, 0, 0));

        txtEmail.setForeground(new java.awt.Color(0, 0, 0));

        txtSodienthoai.setForeground(new java.awt.Color(0, 0, 0));

        txtDiachi.setForeground(new java.awt.Color(0, 0, 0));

        btnTimkiem.setForeground(new java.awt.Color(0, 0, 0));
        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        txtNhaptennv.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nhập tên nhân viên :");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Giới tính :");
        jLabel8.setToolTipText("");

        buttonGroup1.add(radioNam);
        radioNam.setForeground(new java.awt.Color(0, 0, 0));
        radioNam.setText("Nam");

        buttonGroup1.add(radioNu);
        radioNu.setForeground(new java.awt.Color(0, 0, 0));
        radioNu.setText("Nữ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtManhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTennhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtChucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(radioNam)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radioNu)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtSodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNhaptennv, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNhaptennv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimkiem))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel4)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtManhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTennhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtChucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel3)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(radioNam)
                    .addComponent(radioNu))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnLammoi.setForeground(new java.awt.Color(0, 0, 0));
        btnLammoi.setText("Làm mới");
        btnLammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiActionPerformed(evt);
            }
        });

        btnXoa.setForeground(new java.awt.Color(0, 0, 0));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThoat.setForeground(new java.awt.Color(0, 0, 0));
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnThem.setForeground(new java.awt.Color(0, 0, 0));
        btnThem.setText("Thêm ");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThoat)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSua)
                        .addComponent(btnLammoi)
                        .addComponent(btnThem)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadDataToTable() {
        try {
            Nhanvien NhanvienModel = new Nhanvien();
            List<Nhanvien> list = NhanvienModel.getNhanvien();
            // Kiểm tra null trước khi sử dụng equals
            if (NhanvienModel.getgioitinh() != null && NhanvienModel.getgioitinh().equals("Nam")) {
                radioNam.setSelected(true);
            } else {
                radioNu.setSelected(true);
            }
            // Lấy mô hình bảng (table model) và xóa dữ liệu cũ
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tableNhanvien.getModel();
            model.setRowCount(0);

            // Thêm các hàng dữ liệu mới vào bảng
            for (Nhanvien nv : list) {
                model.addRow(new Object[]{
                    nv.getmanv(), nv.gettennv(), nv.getchucvu(),
                    nv.getsdt(), nv.getemail(), nv.getdiachi(), nv.getgioitinh()});
            }
        } catch (SQLException e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu vào bảng.");
        }
    }


    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String manv = txtManhanvien.getText();
        String tennv = txtTennhanvien.getText();
        String chucvu = txtChucvu.getText();
        String sdt = txtSodienthoai.getText();
        String email = txtEmail.getText();
        String diachi = txtDiachi.getText();
        // Đọc giá trị từ radio button
        String gioitinh = radioNam.isSelected() ? "Nam" : "Nữ";

        if (manv.isEmpty() || tennv.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, " vui lòng nhập đầy đủ thông tin ");
        } else {
            try {
                // khởi tạo lớp cho cho table nhanvien
                Nhanvien nhanvien = new Nhanvien();
                //kiểm tra trùng mã nv 
                if (nhanvien.getNhanvien(manv) != null) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Mã loại đã tồn tại. Vui lòng nhập mã khác !");
                    return;
                }
                // Thiet lap  gia trị
                nhanvien.setmanv(manv);
                nhanvien.settennv(tennv);
                nhanvien.setchuvu(chucvu);
                nhanvien.setsdt(sdt);
                nhanvien.setemail(email);
                nhanvien.setdiachi(diachi);
                nhanvien.setgioitinh(gioitinh);

                //goi ham tu lop Nhanvien
                if (nhanvien.InsertData(nhanvien)) {
                    loadDataToTable();
                    txtManhanvien.setText("");
                    txtTennhanvien.setText("");
                    txtChucvu.setText("");
                    txtSodienthoai.setText("");
                    txtEmail.setText("");
                    txtDiachi.setText("");
                    buttonGroup1.clearSelection();
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "thêm thất bại !");
                }
            } catch (Exception e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, " Lỗi !");
            }
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int row = tableNhanvien.getSelectedRow();
        //kiem tra
        if (row != -1) {
            String manv = txtManhanvien.getText();
            String tennv = txtTennhanvien.getText();
            String chucvu = txtChucvu.getText();
            String sdt = txtSodienthoai.getText();
            String email = txtEmail.getText();
            String diachi = txtDiachi.getText();
            // Đọc giá trị từ radio button
            String gioitinh = radioNam.isSelected() ? "Nam" : "Nữ";

            if (manv.isEmpty() || tennv.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin ");
            } else {
                try {
                    Nhanvien nv = new Nhanvien();

                    nv.setmanv(manv);
                    nv.settennv(tennv);
                    nv.setchuvu(chucvu);
                    nv.setsdt(sdt);
                    nv.setemail(email);
                    nv.setdiachi(diachi);
                    nv.setgioitinh(gioitinh);

                    //goi ham 
                    if (nv.EditData(nv)) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Sửa thành công.");
                        //cap nhat vao bang
                        tableNhanvien.setValueAt(manv, row, 0);
                        tableNhanvien.setValueAt(tennv, row, 1);
                        tableNhanvien.setValueAt(chucvu, row, 2);
                        tableNhanvien.setValueAt(sdt, row, 3);
                        tableNhanvien.setValueAt(email, row, 4);
                        tableNhanvien.setValueAt(diachi, row, 5);
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "Sửa thất bại.");
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    javax.swing.JOptionPane.showMessageDialog(this, "Lỗi trong quá trình sửa.");
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn hàng để sửa.");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiActionPerformed

        txtManhanvien.setText("");
        txtTennhanvien.setText("");
        txtChucvu.setText("");
        txtSodienthoai.setText("");
        txtEmail.setText("");
        txtDiachi.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_btnLammoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = tableNhanvien.getSelectedRow();
        if (row != -1) {
            String manv = tableNhanvien.getValueAt(row, 0).toString(); // Lay ma tu table
            try {
                Nhanvien nv = new Nhanvien();
                if (nv.DeleteData(manv)) {
                    javax.swing.JOptionPane.showConfirmDialog(this, " xoa thanh cong !");
                    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tableNhanvien.getModel();
                    model.removeRow(row);
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, " xoa that bai !!!");
                }
            } catch (Exception e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Lỗi trong quá trình xóa.");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn hàng để xóa.");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
      
      
       frTrangChu menu = new frTrangChu();
        menu.setVisible(true);
//        this.setVisible(false);
//         this.dispose();

    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        String Nhaptennv = txtNhaptennv.getText().trim();  // Lấy tên nhập vào từ TextField
        if (Nhaptennv.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập tên nhân viên để tìm kiếm.");
            return;
        }

        try {
            // Tạo đối tượng Nhanvien
            Nhanvien nv = new Nhanvien();

            // Gọi phương thức timKiemNhanVienTheoTen thông qua đối tượng
            List<Nhanvien> dsNhanVien = nv.timKiemNhanVienTheoTen(Nhaptennv);

            // Xóa dữ liệu hiện có trong bảng
            DefaultTableModel modelNhanVien = (DefaultTableModel) tableNhanvien.getModel();
            modelNhanVien.setRowCount(0);

            // Thêm kết quả tìm kiếm vào bảng
            for (Nhanvien n : dsNhanVien) {
                modelNhanVien.addRow(new Object[]{
                    n.getmanv(),
                    n.gettennv(),
                    n.getchucvu(),
                    n.getsdt(),
                    n.getemail(),
                    n.getdiachi(),
                    n.getgioitinh()
                });
            }

            // Hiển thị thông báo nếu không tìm thấy
            if (dsNhanVien.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên nào có tên: " + Nhaptennv);
            }

        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi khi tìm kiếm nhân viên: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void tableNhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNhanvienMouseClicked
        int selectedRow = tableNhanvien.getSelectedRow(); // Lấy chỉ số dòng được chọn

        if (selectedRow != -1) { // Kiểm tra xem có dòng nào được chọn hay không
            String manv = tableNhanvien.getValueAt(selectedRow, 0).toString();
            String tennv = tableNhanvien.getValueAt(selectedRow, 1).toString();
            String chucvu = tableNhanvien.getValueAt(selectedRow, 2).toString();
            String sdt = tableNhanvien.getValueAt(selectedRow, 3).toString();
            String email = tableNhanvien.getValueAt(selectedRow, 4).toString();
            String diachi = tableNhanvien.getValueAt(selectedRow, 5).toString();
            String gioitinh = tableNhanvien.getValueAt(selectedRow, 6).toString();

            // Set các giá trị cho các JTextField
            txtManhanvien.setText(manv);
            txtTennhanvien.setText(tennv);
            txtChucvu.setText(chucvu);
            txtSodienthoai.setText(sdt);
            txtEmail.setText(email);
            txtDiachi.setText(diachi);

            // Đặt giá trị cho RadioButton của giới tính
            if (gioitinh.equals("Nam")) {
                radioNam.setSelected(true);
            } else {
                radioNu.setSelected(true);
            }
        }
    }//GEN-LAST:event_tableNhanvienMouseClicked

    //Phương thức hiển thị kết quả tìm kiếm lên bảng JTable

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLammoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioNam;
    private javax.swing.JRadioButton radioNu;
    private javax.swing.JTable tableNhanvien;
    private javax.swing.JTextField txtChucvu;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtManhanvien;
    private javax.swing.JTextField txtNhaptennv;
    private javax.swing.JTextField txtSodienthoai;
    private javax.swing.JTextField txtTennhanvien;
    // End of variables declaration//GEN-END:variables
}
